# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'techcrunch-hack-sf-2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for techcrunch-hack-sf-2017

  source 'https://github.com/MapQuest/podspecs-ios.git'
  source 'https://github.com/Alamofire/Alamofire.git'

  pod 'MapQuestMaps', '3.4.1-1.3'

  pod 'Alamofire', '~> 4.5.0'
  pod 'SwiftyJSON', '~> 3.1.4'

  target 'techcrunch-hack-sf-2017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'techcrunch-hack-sf-2017UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
