# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'techcrunch-hack-sf-2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for techcrunch-hack-sf-2017

  source 'https://github.com/MapQuest/podspecs-ios.git'
  pod 'MapQuestMaps', '3.4.1-1.3'

  target 'techcrunch-hack-sf-2017Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'techcrunch-hack-sf-2017UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
